### ISSUE TITLE
new_branch를 master로 merge

### ISSUE THREAD

**Issue by jiyun1615** [jiyun1615/Team#13]
new_branch에다가 정리를 조금 해봤는데.. 확인해보고 master에 merge해도 괜찮을지 확인 해주라
@IoTSecure @kkym7569

**Comment by IoTSecure** [comment]
파일이 안보여서 다시 한번 해줄 수 있어?

**Comment by jiyun1615** [comment]
?? 무슨 파일?
opensource 추가한거 안보여??

**Comment by jiyun1615** [comment]
완료
