### ISSUE TITLE
위키에 qt연동 관련한 블로그 링크걸었습니다

### ISSUE THREAD

**Issue by kkym7569** [jiyun1615/Team#20]
연동 안되면 함 해보세요

**Comment by jiyun1615** [comment]
확인~

**Comment by IoTSecure** [comment]
https://www.youtube.com/playlist?list=PLuHgQVnccGMCRv6f8H9K5Xwsdyg4sFSdi

React 쉽게 알려줄 만한 유튭 링크.
폰으로 작업이 안되서 일단 여기다 올려놓을게.
